# Generated by Django 5.2.8 on 2025-11-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'ordering': ['name'], 'verbose_name': 'Blog Category', 'verbose_name_plural': 'Blog Categories'},
        ),
        migrations.AddField(
            model_name='blog',
            name='author_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='blog',
            name='author_title',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='blog',
            name='cta_button_label',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='blog',
            name='cta_button_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='cta_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='extra_categories',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='faqs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='featured_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='hero_kicker_bottom',
            field=models.CharField(blank=True, max_length=260),
        ),
        migrations.AddField(
            model_name='blog',
            name='hero_kicker_top',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='blog',
            name='hero_title',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='blog',
            name='intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='last_updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='main_heading',
            field=models.CharField(blank=True, max_length=260),
        ),
        migrations.AddField(
            model_name='blog',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='read_time',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='sections',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='whats_inside',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(max_length=260, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=240),
        ),
    ]
